### ISSUE TITLE
Support ADPCM sounds

### ISSUE THREAD

**Issue by nathan** [nathan/phosphorus#260]
(Formerly part of #198, but not necessary for a merge)

We need to be able to decode and play ADPCM WAV sounds, since they're quite common and no browser supports them natively.

**Comment by htmlgames** [comment]
Fixed see #494

**Comment by tjvr** [comment]
@htmlgames Have you submitted a PR?

**Comment by htmlgames** [comment]
Hi, slightly off topic - I've made many fixes to my local copy of phosphorus, some of which are work in progress (a simple diff of the phosphorus.js on the website I link to will show this) so I still need to update my github fork (it's currently just a copy of master at the moment) for the wav pcm stuff...

Also, I believe Nathan is aware of this fix and maybe looking into other methods (from comments on other threads) - the fun issue here of course is all the different PCM formats that can be held in a wav container! ... 

btw: recording all sounds in Scratch itself (rather than a third party tool) helps a lot here.
