### ISSUE TITLE
Quads vs Tris - speed comparison for WO997

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#342]
This is the very first project that is (slightly) slower in Phosphorus than in Scratch. Strangely enough, it is almost the same speed in Scratch in turbo mode every time I run it,whereas it varies a lot in Phosphorus when in turbo mode.

http://scratch.mit.edu/projects/51311568/
http://phosphorus.herokuapp.com/#51311568
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by nathan** [comment]
Not at all the results I get. Also, since the frames are >16 ms, turbo mode has essentially no effect.

Scratch:
![screen shot 2015-03-11 at 11 21 30](https://cloud.githubusercontent.com/assets/1578238/6599534/c6b7aac0-c7e0-11e4-87ae-34c3c6889fea.png)

phosphorus:
![screen shot 2015-03-11 at 11 22 16](https://cloud.githubusercontent.com/assets/1578238/6599555/ea63a29e-c7e0-11e4-8df6-43ca86a41ae1.png)

**Comment by sfederici** [comment]
Sorry for answering so late. In my test no turbo times are almost identical in Scratch and Phosphorus, while turbo is really effective. What is weird is that while turbo "tri time" is much lower in Phosphorus, turbo "quad time" is a bit higher in Phosphorus. This is what I get:

Scratch (no turbo)
![screenhunter_665 mar 29 12 54](https://cloud.githubusercontent.com/assets/2651868/6885168/6dd2938e-d613-11e4-97d8-a3530dbc156c.gif)

Scratch (turbo)
![screenhunter_666 mar 29 12 54](https://cloud.githubusercontent.com/assets/2651868/6885171/8786c386-d613-11e4-9e56-a0e7b4f91ac1.gif)

Phosphorus (no turbo)
![screenhunter_667 mar 29 12 55](https://cloud.githubusercontent.com/assets/2651868/6885174/97b10424-d613-11e4-9d33-79538c5402f4.gif)

Phosphorus (turbo)
![screenhunter_668 mar 29 12 56](https://cloud.githubusercontent.com/assets/2651868/6885175/a66915a6-d613-11e4-8278-fa80bc2a03ef.gif)
