### ISSUE TITLE
Tri-fill performance framework

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#364]
This project looks much slower in Phosphorus. Turbo doesn't seem to affect the execution time:

Scratch:
![image](https://cloud.githubusercontent.com/assets/2651868/6935405/f6be3b70-d844-11e4-9395-3ed24e53bddf.png)

Phosphorus:
![image](https://cloud.githubusercontent.com/assets/2651868/6935415/1674a51c-d845-11e4-80c2-34ba377b062b.png)

http://scratch.mit.edu/projects/55095796/
http://phosphorus.github.io/#55095796
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by trumank** [comment]
The problem is that the execution time is set to take more than 1/60 of a second per frame which causes phosphorus to choke. If you change the execution time to 0.1 it will work much better.

**Comment by sfederici** [comment]
I tried. Now Phosphorus looks a little better. But Scratch still looks much better. Is this correct?

**Comment by TheLogFather** [comment]
@sfederici: It's not at all surprising that phosphorus *appears* to be slower - though it's really hugely faster!

The way I've written the framework is that it runs the script to 'draw' as many triangles as it can within the given execution time.

During the script execution there is no actual drawing performed - it's only after the scripts have finished that there's a 'refresh' and the stuff that the scripts said to draw actually gets drawn for real. This happens during the "wait 0" block right after all the rendering.

In the case of Scratch, for the pic above, the script manages to 'pseudo-draw' ~250 tris during that 0.5s. Phosphorus manages ~1400...

These tris then need to be actually sent to the screen. Unfortunately, because of the above behaviour (that the real drawing happens during the "wait 0", and it has all already been decided by the scripts exactly what will get drawn), there's no way to limit the real drawing during the refresh to a certain time - it has to draw all the script said to do. (That's one reason why Scratch can appear to freeze up during non-refresh blocks, even though it's supposed to only allow them to execute for up to half a sec.)

In the case of Scratch, it really draws those ~250 tris in ~0.06s (the 'Render time'). Phosphorus has to draw ~1400 tris, and so it takes much longer, about 0.45s.

One way to compare the speed of Phosphorus for this project would be to try to match the number of triangles produce by each, by changing the allowed execute time. If you bring down the execute time in *just Phosphorus* to around 0.1 then you may get roughly a similar 250 tris drawn by both. Then you can roughly compare the render time too.

**Comment by sfederici** [comment]
Thanks for this explanation :-)
