### ISSUE TITLE
Magnifying Glass

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#679]
The magnifying lens doesn't move.

http://scratch.mit.edu/projects/117006800/
http://phosphorus.github.io/#117006800
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Mittagskogel** [comment]
Are you using a hybrid laptop? (touchscreen and mouse?)

**Comment by sfederici** [comment]
No, just touchpad.

**Comment by Mittagskogel** [comment]
That's weird, are you sure it isn't working? It's working fine for me...

**Comment by sfederici** [comment]
Do you mean the phosphorus version? It doesn't do anything. I can just see a world map with a globe/lens at the center that doesn't move and doesn't follow the mouse as the Scratch version does instead.

**Comment by Mittagskogel** [comment]
What browser are you using? Are you sure you don't have a touchscreen or some other additional input device that might be recognized as a touch screen? It's still working fine for me, the lens is moving. You can try it here if you want: http://newton.nes.aau.at/~sulfurous/#117006800

**Comment by sfederici** [comment]
On Sulfurous it works fine :) Thanks a lot. Which are the updates made to Sulfurous with respect to Phosphorus (I guess Nathan isn't updating and correcting Phosphorous anymore, is it?)

**Comment by Mittagskogel** [comment]
Then really I can only imagine you must be on some sort of hybrid device...?

Sulfurous fixes lots of bugs and slight discrepancies in the execution of Scratch programs. It also adds some graphic effects, although these are quite laggy und should not be overused. (brightness, pixelate, mosaic, and ghost are implemented.) SVG graphics were (partially) fixed. 95% of the SVGs without text should render correctly now. The problem here was that Scratch doesn't seem to follow the SVG spec correctly when saving vector images. The last and probably most important addition is the possibility to change screen sizing for the Package and Embed options. Even the larger sizes do not lose any resolution if you use vector graphics or pen.

Other than that, I will try pushing Sulfurous back to Phosphorus, so if Nathan wants to commit the changes, he can.

**Comment by sfederici** [comment]
Excellent. Thanks for your support to phosphorus :)
