### ISSUE TITLE
State persistance

### ISSUE THREAD

**Issue by entertailion** [nathan/phosphorus#764]
Is it possible to persist the state of the runtime so that it could be used in a cloud function for handling HTTP requests?

**Comment by trumank** [comment]
I'm not exactly sure what you mean. Do you mean saving the state of the project so it can be loaded/resumed again as if you were to save the project in the Scratch editor? Or do you mean hosting a single project on another webpage?

**Comment by entertailion** [comment]
Some context: I'm experimenting using your scratch interpreter/runtime to run some non-visual projects in a shared web server instance (essentially using scratch to create the logic). To support multiple users, the runtime state has to be persisted and restored for each incoming HTTP request since I don't want to dedicate a runtime instance for each user. 

This use case is of course very different from what you have designed it for. I'm using scratch ask/say for doing inputs/outputs. I have a hack where I replay the previous inputs to get the runtime back to the previous state for each incoming request. Having a way to persist the runtime state would be much more efficient.

**Comment by nathan** [comment]
phosphorus wasn't designed to be used as a library (sorry!), which makes things like this tricky, but you should be able to inspect the Stage instance and save/restore any object state you need from that.

Execution state is more complicated, but the only non-serializable thing in the runtime is the continuations. As long as you can guarantee that you're restoring execution state in *exactly* the same project, you can convert continuations to a sprite name and an index in that sprite's `fns` array. (Technically, the functions are serializable as long as you deserialize them with `P.runtime.scopedEval`, but that would inflate the size of the serialized state considerably.)

If you just want to store the state in memory, it's probably better to have an instance per user and cut out all of the drawing/display code, since that's really the only CPU- or memory-intensive thing.

**Comment by entertailion** [comment]
Appreciate the thoughtful feedback for my crazy idea :)
